{{- $fullName := include "moonkat-server.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  defaultBackend:
    service:
      name: {{ $fullName }}
      port:
        number: 8080