apiVersion: v1
kind: Service
metadata:
  name: {{ include "moonkat-server.fullname" . }}
  labels:
    app: {{ include "moonkat-server.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "moonkat-server.fullname" . }}
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080